version: '3.7'

services:
  app:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - 8000:8080
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:latest
    hostname: 'db'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env

volumes:
  postgres_data:
